#!/bin/bash
echo "Create this script on AWS and run it:"
echo ""
echo "#!/bin/bash"
echo "cd /home/ubuntu/agentic-suite/backend"
echo "source .env 2>/dev/null || true"
echo "echo \"MEMORIES_AI_API_KEY present: \${MEMORIES_AI_API_KEY:+YES}\${MEMORIES_AI_API_KEY:-NO}\""
echo "echo \"Key length: \${#MEMORIES_AI_API_KEY}\""
echo ""
echo "# Check if tool file has super().__init__()"
echo "grep -A 2 'def __init__' core/tools/memories_tool.py | head -5"
echo ""
echo "# Check current git commit"
echo "git log --oneline -1"
