name: Deploy to Staging

on:
  push:
    branches:
      - staging
      - develop
  workflow_dispatch:

jobs:
  deploy-backend-staging:
    name: Deploy Backend (Staging)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Backend API
        run: flyctl deploy --config backend/fly.toml --remote-only
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
      
      - name: Deploy Worker
        run: flyctl deploy --config backend/fly.worker.toml --remote-only
        working-directory: backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}

  deploy-frontend-staging:
    name: Deploy Frontend (Staging)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy Frontend
        run: flyctl deploy --remote-only
        working-directory: frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}


